name: rbuy
main: asofold.rbuy.Rbuy
version: 0.1.3 beta
softdepend:
- WorldGuard
- WorldEdit
- admittance

commands:
  rbuy: 
     description: no descrition available
     usage:
  rsell: 
     description: no descrition available
     usage:
  rlist:
     description: no descrition available
     usage:
  rinfo:
     description: no descrition available
     usage:
  rreload:
     description: no descrition available
     usage:
  rhelp:
     description: no descrition available
     usage:
  rdisable:
     description: no descrition available
     usage:
  renable:
     description: no descrition available
     usage:
  rremove:
     description: no descrition available
     usage: