name: rbuy
main: me.asofold.bukkit.rbuy.Rbuy
version: 1.3.0
softdepend:
- WorldGuard
- WorldEdit

commands:
  rbuy: 
     description: 'Buy a region.'
     usage: '/rbuy <region>'
  rsell: 
     description: 'Offer a region for sale, remove own offers, list own offers.'
     usage: 'Place: /rsell <region> <price> [<currency>] | Remove: /rsell <region> | Remove all: /rsell * | List: /rsell'
  rlist:
     description: 'List regions for sale, you can specify a prefix to focus on certain region names.'
     usage: '/rinfo | /rinfo <prefix>'
  rinfo:
     description: 'Get info about nearby offers, or about a specific offer.'
     usage: '/rinfo | /rinfo <region>'
  rreload:
     description: 'Reload the configuration.'
  rhelp:
     description: 'Did i implement this?'
  rdisable:
     description: 'Disable rbuy.'
  renable:
     description: 'Enable rbuy.'
  rremove:
     description: 'Remove offers by player, world, region names.'
     usage: 'use arguments: p:<player> , p:*, w:<world>, w:*, r:<region>, r:*'
  runsellable:
     description: 'Toggle if a region is unsellable.'
     usage: 'Player: /runsellable <rid> OR Player+Console: /runsellable <world> <rid>'
  rcheckoffers:
    description: 'Remove invalid offers, where possible.'
    usage: '/rcheckoffers <world> | /rcheckoffers *'
