name: rbuy
main: me.asofold.bpl.rbuy.Rbuy
version: 2.4.0
softdepend:
- WorldGuard
- WorldEdit

permissions:
  rbuy.filter.command:
    description: Filter permissions to hide commands from tab completion (incomplete).
    children:
      rbuy.filter.command.auction: true
  rbuy.auction:
    description: root node for auction commands.
    children:
      rbuy.filter.command.auction: true
      rbuy.auction.create:
        description: Offer a region by auction.
        children:
          rbuy.filter.command.auction: true
      rbuy.auction.bid:
        description: Allow to bid.
        children:
          rbuy.filter.command.auction: true
      rbuy.auction.withdrawbid:
        description: Allow to withdraw bids.
        children:
          rbuy.filter.command.auction: true
      rbuy.auction.cancelauction:
        description: Allow to cancel auctions.
        children:
          rbuy.filter.command.auction: true
          rbuy.auction.cancelauction.nobids:
            description: Allow to cancel auctions that have no bids.
            children:
              rbuy.filter.command.auction: true

commands:
  rbuy: 
     description: 'Buy a region.'
     usage: '/rbuy <region>'
  rsell: 
     description: 'Offer a region for sale, remove own offers, list own offers.'
     usage: 'Place: /rsell <region> <price> [<currency>] | Remove: /rsell <region> | Remove all: /rsell * | List: /rsell'
  rauction:
    description: 'Offer a region for sale by auction, increase your bid, list your bids (rsell lists offers including auctions, removal also over rsell)'
    permission: rbuy.filter.command.auction
    usage: '/rauction <region> <time>m|h|d <price> [<currency>] | /rauction <region> <price> | /rauction <region> | /rauction | '
  rlist:
     description: 'List regions for sale, you can specify a prefix to focus on certain region names.'
     usage: '/rinfo | /rinfo <prefix>'
  rinfo:
     description: 'Get info about nearby offers, or about a specific offer.'
     usage: '/rinfo | /rinfo <region>'
  rreload:
     description: 'Reload the configuration.'
  rhelp:
     description: 'Did i implement this?'
  rdisable:
     description: 'Disable rbuy.'
  renable:
     description: 'Enable rbuy.'
  rremove:
     description: 'Remove offers by player, world, region names.'
     usage: 'use arguments: p:<player> , p:*, w:<world>, w:*, r:<region>, r:*'
  runsellable:
     description: 'Toggle if a region is unsellable.'
     usage: 'Player: /runsellable <rid> OR Player+Console: /runsellable <world> <rid>'
  rcheckoffers:
    description: 'Remove invalid offers, where possible.'
    usage: '/rcheckoffers <world> | /rcheckoffers *'
  rtransfer:
    description: 'Transfer ownership and offers to another name (useful for server accounts).'
    usage: '/<command> <region|prefix*> <new seller> [<old seller> [<world name|*>]]'