name: rbuy
main: me.asofold.bukkit.rbuy.Rbuy
version: 1.2.0 beta
softdepend:
- WorldGuard
- WorldEdit

commands:
  rbuy: 
     description: no descrition available
  rsell: 
     description: no descrition available
  rlist:
     description: no descrition available
  rinfo:
     description: no descrition available
  rreload:
     description: no descrition available
  rhelp:
     description: no descrition available
  rdisable:
     description: no descrition available
  renable:
     description: no descrition available
  rremove:
     description: no descrition available
  runsellable:
     description: Toggle if a region is unsellable.
     usage: 'Player: /runsellable <rid> OR Player+Console: /runsellable <world> <rid>'
